# Generated by Django 4.2 on 2023-10-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='link',
            field=models.URLField(),
        ),
    ]
