# Generated by Django 4.2 on 2023-10-17 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_app', '0002_alter_vacancy_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
